plugins {
    id 'java'
}

group = 'com.sportradar'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.projectlombok:lombok:$lombokVersion"
    implementation "org.apache.commons:commons-text:$apacheCommonsTextVersion"
    annotationProcessor "org.projectlombok:lombok:$lombokVersion"

    testImplementation "junit:junit:$junitVersion"
    testImplementation "org.assertj:assertj-core:$assertjVersion"
    testImplementation "org.apache.commons:commons-lang3:$apacheCommonsLang3Version"
    testImplementation "org.projectlombok:lombok:$lombokVersion"
    testAnnotationProcessor "org.projectlombok:lombok:$lombokVersion"

}

tasks.named('test') {
}
